INSERT INTO USERS VALUES(1, CURRENT_TIMESTAMP, '나는 남기범입니다', 3, 'nam@naver.com', 'namgibum', '{bcrypt}$2a$10$SjcgOZ3uMZF3HpfWAf9qmuEltdK61pCNrld.oo0i8GQEkh7M3h.Si', 5);
INSERT INTO USERS VALUES(2, CURRENT_TIMESTAMP, '나는 김기홍입니다', 3, 'kim@naver.com', 'kihong', '{bcrypt}$2a$10$SjcgOZ3uMZF3HpfWAf9qmuEltdK61pCNrld.oo0i8GQEkh7M3h.Si', 5);
INSERT INTO USERS VALUES(3, CURRENT_TIMESTAMP, '나는 최주은입니다', 3, 'choi@naver.com', 'teamLeader', '{bcrypt}$2a$10$SjcgOZ3uMZF3HpfWAf9qmuEltdK61pCNrld.oo0i8GQEkh7M3h.Si', 5);
INSERT INTO USERS VALUES(4, CURRENT_TIMESTAMP, '나는 김효중입니다', 3, 'kimhyo@naver.com', 'hyo', '{bcrypt}$2a$10$SjcgOZ3uMZF3HpfWAf9qmuEltdK61pCNrld.oo0i8GQEkh7M3h.Si', 5);
INSERT INTO USERS VALUES(5, CURRENT_TIMESTAMP, '나는 박민경입니다', 3, 'park@naver.com', 'park', '{bcrypt}$2a$10$SjcgOZ3uMZF3HpfWAf9qmuEltdK61pCNrld.oo0i8GQEkh7M3h.Si', 5);

INSERT INTO QUESTION VALUES(1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 30, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 1);
INSERT INTO QUESTION VALUES(2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 2);
INSERT INTO QUESTION VALUES(3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 3);
INSERT INTO QUESTION VALUES(4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 4);
INSERT INTO QUESTION VALUES(5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 5);
INSERT INTO QUESTION VALUES(6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 1);
INSERT INTO QUESTION VALUES(7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 2);
INSERT INTO QUESTION VALUES(8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 3);
INSERT INTO QUESTION VALUES(9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 4);
INSERT INTO QUESTION VALUES(10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 5);
INSERT INTO QUESTION VALUES(11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 1);
INSERT INTO QUESTION VALUES(12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 2);
INSERT INTO QUESTION VALUES(13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 3);
INSERT INTO QUESTION VALUES(14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 4);
INSERT INTO QUESTION VALUES(15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 5);
INSERT INTO QUESTION VALUES(16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 1);
INSERT INTO QUESTION VALUES(17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 2);
INSERT INTO QUESTION VALUES(18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 3);
INSERT INTO QUESTION VALUES(19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 4);
INSERT INTO QUESTION VALUES(20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 5);
INSERT INTO QUESTION VALUES(21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 1);
INSERT INTO QUESTION VALUES(22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 2);
INSERT INTO QUESTION VALUES(23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 3);
INSERT INTO QUESTION VALUES(24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 4);
INSERT INTO QUESTION VALUES(25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '# This is title <br> 1. first <br> 2. second <br> 3. third <br> **focused**', 10, 'title', 100, 5);

INSERT INTO ANSWER VALUES(1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);
INSERT INTO ANSWER VALUES(6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);
INSERT INTO ANSWER VALUES(11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);
INSERT INTO ANSWER VALUES(16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);
INSERT INTO ANSWER VALUES(21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);
INSERT INTO ANSWER VALUES(26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 1);
INSERT INTO ANSWER VALUES(27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 2);
INSERT INTO ANSWER VALUES(28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 3);
INSERT INTO ANSWER VALUES(29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 4);
INSERT INTO ANSWER VALUES(30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'false', 'this is an answer', 10, 1, 5);

INSERT INTO TAG VALUES(1, 'JAVA', 'java', 10);
INSERT INTO TAG VALUES(2, 'JAVA', 'javascript', 10);
INSERT INTO TAG VALUES(3, 'JAVA', 'jpa', 10);
INSERT INTO TAG VALUES(4, 'JAVA', 'sql', 10);
INSERT INTO TAG VALUES(5, 'JAVA', 'springboot', 10);

INSERT INTO QUESTION_TAG VALUES(1, 1, 1);
INSERT INTO QUESTION_TAG VALUES(2, 1, 2);
INSERT INTO QUESTION_TAG VALUES(3, 1, 3);
INSERT INTO QUESTION_TAG VALUES(4, 1, 4);
INSERT INTO QUESTION_TAG VALUES(5, 1, 5);