export const TDummy = [
  {
    id: 1,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 2,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 3,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 4,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 5,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 6,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 7,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 8,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 9,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 10,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 11,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 12,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 13,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 14,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 15,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 16,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 17,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 18,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 19,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 20,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 21,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 22,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 23,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 24,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 25,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 26,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 27,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 28,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '총 질문 수',
    questionCountToday: '오늘 질문 수',
    questionCountWeek: '최근 일주일 질문 수',
  },
  {
    id: 29,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 30,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 31,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 32,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 33,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 34,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 35,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
  {
    id: 36,
    tagName: 'javascript',
    tagDescription: '태그 설명',
    questionCountTotal: '해당 태그가 포함된 질문 수',
    questionCountToday: '오늘 해당 태그가 포함된 질문 수',
    questionCountWeek: '최근 7일 해당 태그가 포함된 질문 수',
  },
];
